// Autocomplete hints for the serial console (the trailing space marks commands that take arguments)
export const commandReference = {
  // --- device ---
  'ver': 'Show firmware version and build date',
  'board': 'Show board name',
  'reboot': 'Reboot device',
  'clkreboot': 'Reset clock to a fixed date and reboot',
  'poweroff': 'Power off device',
  'shutdown': 'Power off device',
  'clock': 'Display current time',
  'time ': 'Set time {epoch-secs} (cannot go backwards)',
  'start ota': 'Start OTA firmware update mode',
  'erase': 'Erase filesystem (factory reset, serial only)',
  'password ': 'Set new admin password',
  'powersaving': 'Show power saving state',
  'powersaving on': 'Enable power saving',
  'powersaving off': 'Disable power saving',

  // --- mesh ---
  'advert': 'Send flood advertisement packet',
  'advert.zerohop': 'Send zero-hop advertisement packet',
  'neighbors': 'List neighbours',
  'neighbor.remove ': 'Remove neighbour {pubkey-hex}',
  'discover.neighbors': 'Send node discovery request (repeater)',
  'tempradio ': 'Temporarily apply radio params {freq,bw,sf,cr,minutes}',

  // --- stats & logging ---
  'stats-core': 'Show battery, uptime, error flags and queue length (JSON)',
  'stats-radio': 'Show noise floor, RSSI, SNR and airtime (JSON)',
  'stats-packets': 'Show packet counters (JSON)',
  'clear stats': 'Reset statistics',
  'log': 'Output packet log',
  'log start': 'Start packet logging to file system',
  'log stop': 'Stop packet logging to file system',
  'log erase': 'Erase the packet logs from file system',

  // --- identity & access ---
  'get public.key': 'Get public key',
  'get prv.key': 'Get private key (serial only)',
  'set prv.key ': 'Set private key {hex} (reboot to apply)',
  'get role': 'Get node role',
  'get guest.password': 'Get guest password',
  'set guest.password ': 'Set guest password',
  'get allow.read.only': 'Get read-only login mode (room server)',
  'set allow.read.only ': 'Set read-only login mode {on|off} (room server)',
  'get acl': 'List access control entries (serial only)',
  'setperm ': 'Set node permissions {pubkey-hex} {0=remove|1=read-only|2=read-write|3=admin}',

  // --- node ---
  'get name': 'Get advertisement name',
  'set name ': 'Set advertisement name',
  'get lat': 'Get the advertisement map latitude',
  'set lat ': 'Set the advertisement map latitude',
  'get lon': 'Get the advertisement map longitude',
  'set lon ': 'Set the advertisement map longitude',
  'get owner.info': 'Get owner info',
  'set owner.info ': 'Set owner info (use | for new line, max 119 bytes)',
  'get repeat': 'Get repeater mode',
  'set repeat ': 'Set repeater mode {on|off}',

  // --- radio ---
  'get radio': 'Get radio params (freq,bw,sf,cr)',
  'set radio ': 'Set radio params {freq,bw,sf,cr} (reboot to apply)',
  'get freq': 'Get frequency (MHz)',
  'set freq ': 'Set frequency {MHz} (reboot to apply)',
  'get tx': 'Get Tx power (dBm)',
  'set tx ': 'Set Tx power {dBm}',
  'get af': 'Get air-time factor',
  'set af ': 'Set air-time factor',
  'get dutycycle': 'Get duty cycle (%)',
  'set dutycycle ': 'Set duty cycle {1-100 %}',
  'get cad': 'Get channel activity detection',
  'set cad ': 'Set channel activity detection {on|off}',
  'get int.thresh': 'Get interference threshold',
  'set int.thresh ': 'Set interference threshold {0-255}',
  'get radio.rxgain': 'Get RX boosted gain',
  'set radio.rxgain ': 'Set RX boosted gain {on|off}',
  'get rxdelay': 'Get RX delay base',
  'set rxdelay ': 'Set RX delay base {0-20}',
  'get txdelay': 'Get flood TX delay factor',
  'set txdelay ': 'Set flood TX delay factor {0-2}',
  'get direct.txdelay': 'Get direct TX delay factor',
  'set direct.txdelay ': 'Set direct TX delay factor {0-2}',
  'get agc.reset.interval': 'Get AGC reset interval (secs)',
  'set agc.reset.interval ': 'Set AGC reset interval {secs, rounded to 4}',
  'get path.hash.mode': 'Get path hash mode',
  'set path.hash.mode ': 'Set path hash mode {0=1-byte|1=2-byte|2=3-byte}',
  'get multi.acks': 'Get multi-ACK mode',
  'set multi.acks ': 'Set multi-ACK mode {0|1}',
  'get extra.sf': 'Get extra spreading factors (LR2021)',
  'set extra.sf ': 'Set extra spreading factors {sf,sf,sf} (LR2021)',
  'get adc.multiplier': 'Get battery ADC multiplier',
  'set adc.multiplier ': 'Set battery ADC multiplier {0=board default}',

  // --- routing & advertising ---
  'get advert.interval': 'Get local advert interval (minutes)',
  'set advert.interval ': 'Set local advert interval {60-240 minutes, 0=off}',
  'get flood.advert.interval': 'Get flood advert interval (hours)',
  'set flood.advert.interval ': 'Set flood advert interval {3-168 hours, 0=off}',
  'get flood.max': 'Get max flood hops',
  'set flood.max ': 'Set max flood hops {0-64}',
  'get flood.max.unscoped': 'Get max flood hops for unscoped packets',
  'set flood.max.unscoped ': 'Set max flood hops for unscoped packets {0-64}',
  'get flood.max.advert': 'Get max flood hops for adverts',
  'set flood.max.advert ': 'Set max flood hops for adverts {0-64}',
  'get loop.detect': 'Get loop detection mode',
  'set loop.detect ': 'Set loop detection mode {off|minimal|moderate|strict}',

  // --- regions ---
  'region': 'Show region tree',
  'region def ': 'Define regions {name[|jump-to] ...}',
  'region load': 'Bulk-import region tree (one indented region per line, blank line commits)',
  'region save': 'Save regions to file system',
  'region put ': 'Add or re-parent region {name} [parent]',
  'region remove ': 'Remove region {name} (must have no children)',
  'region get ': 'Show region {name}',
  'region list ': 'List regions {allowed|denied}',
  'region allowf ': 'Allow flood for region {name}',
  'region denyf ': 'Deny flood for region {name}',
  'region home': 'Show home region',
  'region home ': 'Set home region {name}',
  'region default': 'Show default region',
  'region default ': 'Set default region {name|<null>}',

  // --- gps ---
  'gps': 'Show GPS status',
  'gps on': 'Enable GPS',
  'gps off': 'Disable GPS',
  'gps sync': 'Sync clock from GPS',
  'gps setloc': 'Set advert location from GPS fix',
  'gps advert': 'Show GPS advert location policy',
  'gps advert ': 'Set GPS advert location policy {none|share|prefs}',

  // --- sensors ---
  'sensor list': 'List sensor settings [start-index]',
  'sensor get ': 'Get sensor setting {key}',
  'sensor set ': 'Set sensor setting {key} {value}',

  // --- bridge ---
  'get bridge.type': 'Get bridge type (rs232|espnow|none)',
  'get bridge.enabled': 'Get bridge state',
  'set bridge.enabled ': 'Set bridge state {on|off}',
  'get bridge.delay': 'Get bridge delay (ms)',
  'set bridge.delay ': 'Set bridge delay {0-10000 ms}',
  'get bridge.source': 'Get bridge packet source',
  'set bridge.source ': 'Set bridge packet source {tx|rx}',
  'get bridge.baud': 'Get RS232 bridge baud rate',
  'set bridge.baud ': 'Set RS232 bridge baud rate {9600-115200}',
  'get bridge.channel': 'Get ESP-NOW bridge channel',
  'set bridge.channel ': 'Set ESP-NOW bridge channel {1-14}',
  'get bridge.secret': 'Get ESP-NOW bridge secret',
  'set bridge.secret ': 'Set ESP-NOW bridge secret',

  // --- power / platform ---
  'get bootloader.ver': 'Get bootloader version (nRF52)',
  'get pwrmgt.support': 'Get power management support',
  'get pwrmgt.source': 'Get power source (external|battery)',
  'get pwrmgt.bootreason': 'Get last reset and shutdown reason',
  'get pwrmgt.bootmv': 'Get boot voltage (mV)',
};
